# Generated by Django 2.2.2 on 2019-06-05 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('rut_paciente', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellido_pat', models.CharField(max_length=100)),
                ('apellido_mat', models.CharField(max_length=100)),
                ('fecha_nac', models.DateField()),
                ('ocupacion', models.CharField(max_length=100)),
                ('estado_civil', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.IntegerField()),
                ('prevision', models.CharField(max_length=200)),
            ],
        ),
    ]
