# Generated by Django 2.2.2 on 2019-06-14 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_agendarexamen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Espacialista',
            fields=[
                ('rut_especialista', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('fecha_nac', models.DateField()),
                ('sexo', models.CharField(choices=[('Femenino', 'Femenino'), ('Masculino', 'Masculino')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='TipoExamen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_examen', models.CharField(choices=[('Examen tipo 1', 'Examen tipo 1'), ('Examen tipo 2', 'Examen tipo 2'), ('Examen tipo 3', 'Examen tipo 3'), ('Examen tipo 4', 'Examen tipo 4'), ('Examen tipo 5', 'Examen tipo 5'), ('Examen tipo 6', 'Examen tipo 6')], max_length=2)),
                ('duracion', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('descripcion', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(max_length=300)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.Espacialista')),
                ('tipo_examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.TipoExamen')),
            ],
        ),
    ]
